

import "./globals.css";

import LayoutWrapper from "@/components/LayoutWrapper";


export const metadata = {
  title: "Frieds-Tracker-next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      
      <body className="min-h-full flex flex-col">
        <div className="max-w-[1600px] mx-auto w-full">
       
            <LayoutWrapper>{children}</LayoutWrapper>
        </div>
        </body>
      
    </html>
  );
}
